version: "3.8"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:80
    environment:
      - DB_NAME=book_store_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - pg
  pg:
    container_name: pg_container
    image: postgres:13.2-alpine
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: book_store_db
        POSTGRES_HOST_AUTH_METHOD: trust
    ports:
        - "5432:5432"
    volumes:
        - ./data:/data
        - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: